### ISSUE TITLE
Simpler Config File

### ISSUE THREAD

**Issue by DavJCosby** [DavJCosby/sled#79]
The current config file is really verbose and supports some niceties that aren't really necessary (like per-strip densities).

Here's what a config file may look like right now:
```toml
center_point = [0.0, 1.0]
density = 30.0

[[line_segment]]
start = [-2.0, 0.0]
end = [0.5, -1.0]

[[line_segment]]
start = [0.5, -1.0]
end = [3.5, 0.0]

[[line_segment]]
start = [3.5, 0.0]
end = [2, 2]

[[line_segment]]
start = [2.0, 2]
end = [-2.0, 2]

[[line_segment]]
start = [-2.0, 2]
end = [-2.0, 0.0]
```

Here's what I propose:
```yaml
center: (0, 0.5)
density: 30
--segments--
(-2, 0) --> (0.5, -1) --> (3.5, 0) -->
(2, 2) --> (-2, 2) --> (-2, 0)
```

Whitespace and linebreaks are irrelevant for the segments section. The entire thing can be all on one line, or broken across several.

If you want unconnected line segments, you'd replace the connection particle `-->` with a the separator `|`. Like this:
```yaml
(-2, 0) --> (0.5, -1) --> (3.5, 0) |
(2, 2) --> (-2, 2) --> (-2, 0)
```

Another benefit of this switch is the ability to drop `serde` as a dependency.
